apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/observability/otel-collector
- ../../base/observability/prometheus
- ../../base/observability/grafana
- ../../base/apps/layer-4-analysis

namespace: trading-system
